name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - "Aarush;)" # Ya jo bhi aapki main branch hai
      - "main"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.41.7'

      - name: Install Dependencies
        run: flutter pub get

      - name: Create .env file for AI Service
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > .env
          echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> .env
          echo "FIREBASE_PROJECT_ID=mediflow-92e6f" >> .env
          echo "FIREBASE_AUTH_DOMAIN=mediflow-92e6f.firebaseapp.com" >> .env
          echo "FIREBASE_STORAGE_BUCKET=mediflow-92e6f.firebasestorage.app" >> .env
          echo "FIREBASE_MESSAGING_SENDER_ID=71200393927" >> .env
          echo "FIREBASE_APP_ID=1:71200393927:web:346d720af6b9cf11898ce2" >> .env

      - name: Build Web App
        run: flutter build web --release --base-href /

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting --project mediflow-92e6f
